const SHOP_DATA = {
	oils: {
		id: 1,
		title: "Oils",
		routeName: "oils",
		items: [
			{
				id: 1,
				name: "Almond Oil",
				type: "oils",
				imageUrl: "https://i.ibb.co/bRYN3Bx/Almond-Oil.png",
				price: "130 - 2600",
				routeName: "almondoil",
			},
			{
				id: 2,
				name: "Walnut Oil",
				type: "oils",
				imageUrl: "https://i.ibb.co/mG3cFn6/Walnut-Oil.jpg",
				price: "130 - 2600",
				routeName: "walnutoil",
			},
			{
				id: 3,
				name: "Groundnut Oil",
				type: "oils",
				imageUrl: "https://i.ibb.co/8z8DvY6/Groundnut-Oil.jpg",
				price: "190 - 2300",
				routeName: "groundnutoil",
			},
			{
				id: 4,
				name: "Mustard Oil",
				type: "oils",
				imageUrl: "https://i.ibb.co/c1bkZPh/Mustard-Oil.png",
				price: "80 - 190",
				routeName: "mustardoil",
			},
			{
				id: 5,
				name: "Coconut Oil",
				type: "oils",
				imageUrl: "https://i.ibb.co/cb17y30/Coconut-Oil.png",
				price: "110 - 1525",
				routeName: "coconutoil",
			},
			{
				id: 6,
				name: "Flaxseed Oil",
				type: "oils",
				imageUrl: "https://i.ibb.co/Xz8MgDY/Flaxseed-Oil.png",
				price: "120 - 200",
				routeName: "flaxseedoil",
			},
			{
				id: 7,
				name: "Black Til (Sesame) Oil",
				type: "oils",
				imageUrl: "https://i.ibb.co/GTW0BDQ/Black-Sesame-Oil.png",
				price: "120",
				routeName: "blacktiloil",
			},
			{
				id: 8,
				name: "White Til (Sesame) Oil",
				type: "oils",
				imageUrl: "https://i.ibb.co/CQMmWwH/White-Sesame-Oil.png",
				price: "110 - 3520",
				routeName: "whitetiloil",
			},
			{
				id: 9,
				name: "Diva Til Oil",
				type: "oils",
				imageUrl: "https://i.ibb.co/VLPzqLL/Diva-Til-Oil.jpg",
				price: "95 - 180",
				routeName: "divatiloil",
			},
			{
				id: 10,
				name: "Kardai (Safflower) Oil",
				type: "oils",
				imageUrl: "https://i.ibb.co/880spJS/Kardi-Oil.png",
				price: "200 - 2350",
				routeName: "kardaioil",
			},
		],
	},
	scrubs: {
		id: 2,
		title: "Scrubs",
		routeName: "scrubs",
		items: [
			{
				id: 11,
				name: "Almond and Walnut Scrub",
				type: "scrubs",
				imageUrl: "https://i.ibb.co/0MYw2Ms/Almond-Walnut-Scrub.jpg",
				price: "40",
				routeName: "almondandwalnutscrub",
			},
			{
				id: 12,
				name: "Coconut Scrub",
				type: "scrubs",
				imageUrl: "https://i.ibb.co/0MYw2Ms/Almond-Walnut-Scrub.jpg",
				price: "30",
				routeName: "coconutscrub",
			},
		],
	},
	flours: {
		id: 3,
		title: "Flours",
		routeName: "flours",
		items: [
			{
				id: 13,
				name: "Almond Flour",
				type: "flours",
				imageUrl: "https://i.ibb.co/jHbfZH1/Almond-Flour.jpg",
				price: "35 - 75",
				routeName: "almondflour",
			},
			{
				id: 14,
				name: "Coconut Flour",
				type: "flours",
				imageUrl: "https://i.ibb.co/bX6s51n/Coconut-Flour.jpg",
				price: "25",
				routeName: "coconutflour",
			},
			{
				id: 15,
				name: "Flaxseed Flour",
				type: "flours",
				imageUrl: "https://i.ibb.co/p45fT9B/Flaxseed-Flour.jpg",
				price: "25",
				routeName: "flaxseedflour",
			},
		],
	},
	other: {
		id: 4,
		title: "Other",
		routeName: "other",
		items: [
			{
				id: 16,
				name: "Awala Ginger",
				type: "other",
				imageUrl: "https://i.ibb.co/5Mj06jn/Awala-Ginger.jpg",
				price: "75",
				routeName: "awalaginger",
			},
			{
				id: 17,
				name: "Jaggery Powder",
				type: "other",
				imageUrl: "https://i.ibb.co/SQLqvkK/Jaggery-Powder.jpg",
				price: "55 - 80",
				routeName: "jaggerypowder",
			},
			{
				id: 18,
				name: "Raw Sesame Seeds",
				type: "other",
				imageUrl: "https://i.ibb.co/yWfN41n/Raw-Sesame-Seed.jpg",
				price: "30 - 120",
				routeName: "rawsesameseeds",
			},
			{
				id: 19,
				name: "Roasted Flax Seed Turmeric",
				type: "other",
				imageUrl: "https://i.ibb.co/CHb8rhf/Roasted-Flaxseed-Turmeric.jpg",
				price: "65",
				routeName: "roastedflaxseedturmeric",
			},
			{
				id: 20,
				name: "Rock Salt (Saindhav)",
				type: "other",
				imageUrl: "https://i.ibb.co/xH2k4ks/Rock-Salt.jpg",
				price: "50 - 90",
				routeName: "rocksalt",
			},
		],
	},
};

export default SHOP_DATA;
